# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyConvertor' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CurrencyConvertor
pod ‘CurrencyRequest’ , ‘~> 0.1’

end
